<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZKU8Nak\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZKU8Nak/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZKU8Nak.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZKU8Nak\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZKU8Nak\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZKU8Nak',
    'container.build_id' => 'cb120d1f',
    'container.build_time' => 1717593173,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZKU8Nak');
